name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main # or any branch you prefer

jobs:
  deploy:
    name: Build & Deploy to AWS App Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to AWS App Runner
        env:
          SERVICE_ARN: ${{ secrets.APP_RUNNER_ARN }}
          ECR_IMAGE: ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        run: |
          aws apprunner update-service \
            --service-arn $SERVICE_ARN \
            --source-configuration ImageRepository={ImageIdentifier=$ECR_IMAGE,ImageRepositoryType=ECR} \
            --auto-deployments-enabled
