name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main # or whichever branch you deploy from

jobs:
  deploy:
    name: Build & Push to ECR (App Runner auto-deploy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} # e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:latest

      - name: Echo
        run: echo "✅ Pushed image to ECR. App Runner will auto-deploy from ECR:latest"
